### ISSUE TITLE
better frontend project structure

### ISSUE THREAD

**Issue by eikib** [OptiCorp/TurbinSikker-App#149]
# Refactor
### API
- [x] Make API service #211 
- [x] Make types for api calls #211
### Context
- [x] Replace all contexts with one global context 
       #220
    - [x] #216
    - [x] Refactor global context (max 100~ lines?)

### Hooks
- [x] Refactor hooks
(_Replace hook with helper if hook is not necessary_)
    - [x] #265 [[REFACTOR]: Snackbar](https://github.com/OptiCorp/TurbinSikker-App/pull/265)

### Styles
- [x] #234 [add a GlobalStyles](https://github.com/OptiCorp/TurbinSikker-App/issues/234)
- [x] #238 
- [x] #239 
- [x] #251 
- [x] #263 
- [x] #273
- [x] #268 
    - [x] #276
- [x] #278
- [x] #286
- [x] #280    
- [x] #246 [Using COLORS from GlobalStyles 
                 (addTasks, Header, navItem, navigation, sidebar, doneWorkflows, editHeader, editChecklist, checklist, myChecklists, leaderMyChecklists, previewChecklist, sendChecklist, leaderChecklistSend, submittedChecklists, workflowAddPunch)](https://github.com/OptiCorp/TurbinSikker-App/pull/246)

### LOADING, SUCCESS, ERROR
(_Add a state for each page based on status from **API**_)
- [X] Loading & Success #221 

### Naming
(better variable, folder etc naming)
- Folders: camelCase
    - [x] #244 
- Components: PascalCase

**Comment by bjornole-kodehode** [comment]
- [ ] Replace all contexts with one global context
- [ ] Refactor hooks
- [ ] Refactor styles, add a GlobalStyles
